# 예외처리

> 프로그램 실행중 예기치 못한 사건을 예회라고 한다. 예회 상황을 미치 예측하고 처리할 수 있는데, 이렇게 하는 것을 예외 처리라고 한다.

```java
try{ //수행할 코드, 예외 발생 가능성이 있는 블록
  ...
} catch(예외클래스 변수명){ // 예외 처리블록
  ...
} finally{ //예외 발생여부에 상관없이 반드시 실행되는 블록
  ...
}
```

```java
    public class ExceptionExam {
        public static void main(String[] args) {
            int i = 10;
            int j = 0;
            try{
                int k = i / j;
                System.out.println(k);
            }catch(ArithmeticException e){
                System.out.println("0으로 나눌 수 없습니다. : " + e.toString());
            }finally {
                System.out.println("오류가 발생하든 안하든 무조건 실행되는 블록입니다.");
            }
        }
    }
```



#### Throws

> throws 는 예외가 발생했을 때 예외를 호출한 쪽에서 처리하도록 던져준다.

```java
    public class ExceptionExam2 {

        public static void main(String[] args) {
            int i = 10;
            int j = 0;
            try{
                int k = divide(i, j);
                System.out.println(k);
            } catch(ArithmeticException e){
                System.out.println("0으로 나눌수 없습니다.");
            }

        }
				//divide메소드는 ArithmeticException이 발생하니 divide메소드를 
      	//호출하는 쪽에서 오류를 처리하라는 뜻
        public static int divide(int i, int j) throws ArithmeticException{
            int k = i / j;
            return k;
        }

    }
```





#### Throw

> 강제로 오류를 발생시킨다 

* divide 메소드 뒤에 throws IllegalArgumentException 은 해당 오류는 divide를 호출한 쪽에서 처리를 해야한다는 것을 의미

```java
public class ExceptionExam3 {   
        public static void main(String[] args) {
            int i = 10;
            int j = 0;
            try{
                int k = divide(i, j);
                System.out.println(k);
            }catch(IllegalArgumentException e){
                System.out.println("0으로 나누면 안됩니다.");
            }           
        }

public static int divide(int i, int j) throws IllegalArgumentException{
            if(j == 0){
                throw new IllegalArgumentException("0으로 나눌 수 없어요.");
            }
            int k = i / j;
            return k;
        }   
    }
```



#### 사용자정의 Exception

* Exceotion이나 Exception의 후손을 상속받아 만들어진 클래스
* 클래스의 이름만으로 어떤 오류가 발생했는지 알려주어 코드의 직관서을 높인다.

```java
public class 클래스 이름 extends Exception {
  ...
}
```





### try-with-resource

> close는 워낙 자주 해야 하는 일이고, 너무 중요한 일이기 때문에 java 7 부터 자동으로 close를 해주는 try-with-resource 가 추가됨 

개선전 코드

```java
import com.sun.xml.internal.ws.policy.privateutil.PolicyUtils;
 
import java.io.FileWriter;
import java.io.IOException;
 
public class CheckedExceptionApp {
    public static void main(String[] args) {
        FileWriter f = null;
        try {
            f = new FileWriter("data.txt");
            f.write("Hello");
        } catch(IOException e){
            e.printStackTrace();
        } finally {
            // 만약에 f가 null이 아니라면
            if(f  != null) {
                try {
                    f.close();
                } catch(IOException e){
                    e.printStackTrace();
                }
            }
        }
    }
}
```



개선후 코드

```java
import java.io.FileWriter;
import java.io.IOException;
 
public class TryWithResource {
    public static void main(String[] args) {
        // try with resource statements
        try (FileWriter f = new FileWriter("data.txt")) {
            f.write("Hello");
        } catch(IOException e){
            e.printStackTrace();
        }
    }
}
```

